<a href="https://colab.research.google.com/github/srinijadharani/Python-for-ML-and-Data-Science/blob/master/Day1(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PYTHON FOR DATA ANALYSIS - NUMPY (SECTION-5)**

### **NumPy Arrays**<br>
Outputs of all the functions shown here are stored in arrays.

In [1]:
mylist = [1,2,3]

Importing numpy package as np. We can use np with fucntions to generate the outputs that we want. array() is a function that converts the given input into an array. We can even generate a 3X3 matrix and a 1D vector.<br>
Vectors are identified by single [ ]. Matrices have two [ ] or more.

In [2]:
import numpy as np
arr = np.array(mylist)
arr

array([1, 2, 3])

In [3]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arange() is the same as range() function in vanilla Python. 
`arange(start,stop,step)`

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros() helps us print how many ever zeros we want. We can print 1D vector and matrices too. To print a matrix with zeros, pass in to the fucntion zeros() a tuple.<br>
For example, zeros((2,2))

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Similarly, if you want to print a matrix or a vector containing only 1s, use the function ones(). The parameters are the same as zeros().

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

The linspace() function returns evenly spaced numbers over a specified interval [start, stop].
The endpoint of the interval can optionally be excluded.

In [11]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

`eye()` prints an identity matrix of given order. Identity matirx is a square matrix and all the diagonal elements are 1s and the rest elements are 0s. The whole matrix is stored in an array.

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Random Library: `random.rand(n)` prints random values and stores them in an array. `n` is the number of values we want to display.

In [13]:
np.random.rand(3)

array([0.54996826, 0.30122855, 0.91349313])

In [14]:
np.random.rand(3,3) #no need of passing this argument in a tuple.

array([[0.83300514, 0.62898239, 0.25185699],
       [0.07977993, 0.74681931, 0.5682437 ],
       [0.50863962, 0.38525586, 0.60978443]])

`random.randn()` prints values not from a uniform distribution but fron a standard normal distribution.

In [15]:
np.random.randn(2)

array([-0.05780458, -1.13581128])

In [16]:
np.random.randn(3,3)

array([[-1.45234937,  0.97572675,  0.0470141 ],
       [-1.0407462 ,  0.20441572, -0.57195403],
       [-0.04053941, -0.9018634 ,  0.34711145]])

`random.randint(start, stop, n)` prints radom values from start to stop (stop exclusive). n is the number of values that are being printed.

In [17]:
np.random.randint(1,100,10)

array([57, 38, 89, 52, 68,  8,  3, 67, 64, 81])

`reshape()`: This function allows us to reshape the array that we have previously printed. Remember, the argument value should not exceed that of the length of the array. The number of elements in the array is equal to the product of the two arguments we pass in reshape().

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr = np.arange(9)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

`max()` and `min()` are used to display the maximum and the minimum values (respectively) of an array.

In [24]:
arr.max()

8

In [25]:
arr.min()

0

In [26]:
arr.argmax() #returns the index position of the maximum value 

8

In [27]:
arr.argmin() #returns the index position of the minimum value

0

In [28]:
matrix = arr.reshape(3,3)

In [29]:
arr.shape #the plain array - vector

(9,)

In [30]:
matrix.shape #the matrix - 2D array

(3, 3)

In [31]:
arr.dtype #to find out what data type the array is. Here, it's a 64 bit integer array

dtype('int64')

In [32]:
matrix.dtype

dtype('int64')

## **NumPy Array Selecting and Indexing**

In [33]:
import numpy as np

In [34]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
arr[4]

8

In [37]:
arr[0:5]

array([0, 2, 4, 6, 8])

In [38]:
arr[0:7:2]

array([ 0,  4,  8, 12])

In [39]:
arr[::-1]

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [40]:
arr[:7]

array([ 0,  2,  4,  6,  8, 10, 12])

In [41]:
arr[2:]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
arr[0:5] = 200

In [43]:
arr

array([200, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20])

In [44]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
arr_slice = arr[0:6]
arr_slice

array([ 0,  2,  4,  6,  8, 10])

In [46]:
arr_slice[:] = 100

In [47]:
arr_slice

array([100, 100, 100, 100, 100, 100])

In [48]:
arr_slice = arr[0:6]
arr_slice
arr_slice[:] = 99

In [49]:
arr_slice

array([99, 99, 99, 99, 99, 99])

In [50]:
arr

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

Here, we notice that even though we changed the elements in the sliced array, the elements of the original array are also getting changed. This means that the sliced array is not a copy of a slice of the original array but it is a view of the original. And the reason why NumPy does that is to avoid memory issues with very large arrays.<br>
If you don't want a reference of the actual array, we can use the `copy()` function.

In [51]:
arr

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

In [52]:
arr_copy = arr.copy()

In [53]:
arr_copy[:] = 100 #set all values to 100

In [54]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
arr

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

The original array is unaffected. Changes made to the copied array will not be reflected on `arr`.

## **Indexing- 2D Array**<br>
1. Double bracket format
2. Single bracket format

In [56]:
import numpy as np

In [57]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr_2d[1][2] #to print '6' (double bracket format)

6

In [60]:
arr_2d[1]

array([4, 5, 6])

In [61]:
arr_2d[0][2]

3

In [62]:
arr_2d[0,2] #single bracket format #best practice

3

In [63]:
arr_2d[2,2]

9

In [64]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [65]:
arr_2d[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
bool_arr = arr > 4

In [69]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [70]:
arr[bool_arr] #this only returns the values where bool == True

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr < 3]

array([0, 1, 2])

In [73]:
arr_2d = np.arange(0,50).reshape(5,10)

In [74]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr_2d[0,1:4]

array([1, 2, 3])

In [76]:
arr_2d[3:4,6:10]

array([[36, 37, 38, 39]])

In [77]:
arr_2d[3:5,6:10]

array([[36, 37, 38, 39],
       [46, 47, 48, 49]])

## **NumPy Operations (perform on NumPy arrays)**

In [78]:
import numpy as np

In [79]:
arr = np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + arr #add each element of arr to itself

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
arr + 100 #adds 100 to each element of arr, but this won't affect the original array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [85]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

An error will be thrown (in vanilla python) if we try to divide a number by 0. But in NumPy, a warning will be generated instead of an error.

In [87]:
arr / arr #0/0 doesn't make sense

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [88]:
1 / arr #the output will be infinity for 1/0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

**Universal Array Functions**<br>
You can perform an operation using these functions and broadcast it across the array.

In [89]:
np.sqrt(arr) #square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [90]:
np.exp(arr) #e^arr[i]

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [91]:
np.max(arr)

10

In [92]:
np.min(arr)

0

In [93]:
np.sin(arr) #sin(arr[i])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [94]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])