<a href="https://colab.research.google.com/github/srinijadharani/Python-for-ML-and-DS/blob/master/Practice%2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Arrays**


In [1]:
import numpy as np

In [3]:
mylist=[1,2,3]
arr=np.array(mylist)
print(arr, type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
mymatrix=[[0,1,2],[3,4,5],[6,7,8]]
mat=np.array(mymatrix)
print(mat, type(mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [5]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(3)

array([0.5103888 , 0.13716027, 0.23261804])

In [23]:
np.random.rand(3,3)

array([[0.21889698, 0.2472062 , 0.52939655],
       [0.42674037, 0.8244793 , 0.8191634 ],
       [0.60323821, 0.74190058, 0.49036746]])

In [24]:
np.random.randn(3)

array([-1.5944898 ,  0.88222016, -2.36749066])

In [25]:
np.random.randn(3,3)

array([[-1.00282412,  0.13558037,  0.17203899],
       [-0.11818761,  0.70725895, -0.86421681],
       [-0.26971217, -0.86362652, -1.76483046]])

In [26]:
np.random.randint(0,100,2)

array([37,  0])

In [27]:
np.random.randint(0,100,9)

array([58, 23, 50, 62, 14, 21, 95, 98, 85])

In [31]:
arr=np.arange(1,26)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [32]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr=np.arange(1,10)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
randarr=np.random.randint(0,100,10)

In [45]:
randarr

array([84, 52, 33, 47, 86,  9, 67, 22, 27, 26])

In [46]:
randarr.max()

86

In [47]:
randarr.min()

9

In [48]:
randarr.argmax() #index of the max value

4

In [49]:
randarr.argmin()

5

In [50]:
arr=np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[0:4]

array([0, 1, 2, 3])

In [56]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [57]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [61]:
arr[0:7:3]

array([0, 3, 6])

In [63]:
arr[0:3]= 1000

In [64]:
arr

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [65]:
arr[:]=100

In [67]:
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]


In [68]:
arr=np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr_copy=arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:]=100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
mylist=[[0,1,2],[3,4,5],[6,7,8]]
arr=np.array(mylist)

In [75]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr[0][1]

1

In [77]:
arr[2][2]

8

In [81]:
arr[1:2]

array([[3, 4, 5]])

In [84]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [87]:
arr[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [88]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [92]:
arr=np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr=np.arange(0,11)

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [96]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [97]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# **PANDAS**