<a href="https://colab.research.google.com/github/srinijadharani/Python-for-ML-and-DS/blob/master/Practice%2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Arrays**


In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]
arr=np.array(mylist)
print(arr, type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
mymatrix=[[0,1,2],[3,4,5],[6,7,8]]
mat=np.array(mymatrix)
print(mat, type(mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3)

array([0.09124978, 0.44745295, 0.48126615])

In [16]:
np.random.rand(3,3)

array([[0.36464554, 0.07734687, 0.61642325],
       [0.0837405 , 0.02499842, 0.33512862],
       [0.14897589, 0.60301553, 0.90324402]])

In [17]:
np.random.randn(3)

array([-0.18850401, -1.08672031,  0.78825378])

In [18]:
np.random.randn(3,3)

array([[-1.36699529, -2.2788924 , -2.28370703],
       [-0.50172119,  0.92475039,  0.61372906],
       [-1.31987027,  2.62229003,  0.58599194]])

In [19]:
np.random.randint(0,100,2)

array([40, 91])

In [20]:
np.random.randint(0,100,9)

array([53, 93, 48, 15, 78, 64, 25, 21, 23])

In [21]:
arr=np.arange(1,26)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [22]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr=np.arange(1,10)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
randarr=np.random.randint(0,100,10)

In [25]:
randarr

array([17, 27, 45, 69, 24, 44, 86, 53, 74, 37])

In [26]:
randarr.max()

86

In [27]:
randarr.min()

17

In [28]:
randarr.argmax() #index of the max value

6

In [29]:
randarr.argmin()

0

In [30]:
arr=np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[0:4]

array([0, 1, 2, 3])

In [33]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [34]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [36]:
arr[0:7:3]

array([0, 3, 6])

In [37]:
arr[0:3]= 1000

In [38]:
arr

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [39]:
arr[:]=100

In [40]:
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]


In [41]:
arr=np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr_copy=arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr_copy[:]=100

In [45]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
mylist=[[0,1,2],[3,4,5],[6,7,8]]
arr=np.array(mylist)

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[0][1]

1

In [50]:
arr[2][2]

8

In [51]:
arr[1:2]

array([[3, 4, 5]])

In [52]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [54]:
arr[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [55]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [57]:
arr=np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr=np.arange(0,11)

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# **PANDAS**

In [62]:
import pandas as pd

In [63]:
mydata=np.arange(0,6)
pd.Series(data=mydata)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [64]:
mydata=[100,200,300,400,500,600]
pd.Series(data=mydata)

0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

In [65]:
mydict={"ten":10, "twenty":20, "thirty":30, "forty":40}
pd.Series(data=mydict)

ten       10
twenty    20
thirty    30
forty     40
dtype: int64

In [66]:
labels=["a","b","c","d"]
mydata=[1,2,3,4]
series=pd.Series(index=labels, data=mydata)

In [67]:
print(series)

a    1
b    2
c    3
d    4
dtype: int64


In [68]:
ser1=pd.Series([1,2,3,4],["one","two","three","four"])

In [69]:
ser2=pd.Series([1,2,3,4],["one","hello","three","ciao"])

In [70]:
print(ser1+ser2)

ciao     NaN
four     NaN
hello    NaN
one      2.0
three    6.0
two      NaN
dtype: float64


In [71]:
np.random.seed(101)

In [72]:
df=pd.DataFrame(np.random.randn(5,5),["A","B","C","D","E"],["P","Q","R","S","T"])

In [73]:
df

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [74]:
df["P"]

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
Name: P, dtype: float64

In [76]:
df["R"]

A    0.907969
B    0.605965
C    0.188695
D    1.978757
E   -1.706086
Name: R, dtype: float64

In [78]:
type(df["R"])

pandas.core.series.Series

In [79]:
type(df)

pandas.core.frame.DataFrame

In [80]:
df[["P","S"]]

P         S
A  2.706850  0.503826
B -0.319318 -2.018168
C  0.528813 -0.758872
D  0.955057  2.605967
E  0.302665 -1.159119

In [81]:
df["new"]=df["P"]+df["Q"]

In [82]:
df

P         Q         R         S         T       new
A  2.706850  0.628133  0.907969  0.503826  0.651118  3.334983
B -0.319318 -0.848077  0.605965 -2.018168  0.740122 -1.167395
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -0.060187
D  0.955057  0.190794  1.978757  2.605967  0.683509  1.145851
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841  1.996388

In [84]:
df.drop("new", axis=1)

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [85]:
df

P         Q         R         S         T       new
A  2.706850  0.628133  0.907969  0.503826  0.651118  3.334983
B -0.319318 -0.848077  0.605965 -2.018168  0.740122 -1.167395
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -0.060187
D  0.955057  0.190794  1.978757  2.605967  0.683509  1.145851
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841  1.996388

In [86]:
df.drop("new", axis=1, inplace=True)

In [87]:
df

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [89]:
df.shape

(5, 5)

In [93]:
df.loc["B"] #for rows

P   -0.319318
Q   -0.848077
R    0.605965
S   -2.018168
T    0.740122
Name: B, dtype: float64

In [94]:
df.iloc[1] #for rows using indices

P   -0.319318
Q   -0.848077
R    0.605965
S   -2.018168
T    0.740122
Name: B, dtype: float64

In [95]:
df["S"]["A"]

0.5038257538223936

In [102]:
df.loc[["B","E"],["P","T"]]

P         T
B -0.319318  0.740122
E  0.302665 -0.134841

In [104]:
df

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [105]:
df>0

P      Q      R      S      T
A   True   True   True   True   True
B  False  False   True  False   True
C   True  False   True  False  False
D   True   True   True   True   True
E   True   True  False  False  False

In [106]:
df[df>0]

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B       NaN       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN       NaN
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723       NaN       NaN       NaN

In [111]:
df[df>0][["P","Q"]]

P         Q
A  2.706850  0.628133
B       NaN       NaN
C  0.528813       NaN
D  0.955057  0.190794
E  0.302665  1.693723

In [116]:
p_col=df["P"]>0
q_col=df["Q"]<0
df[(p_col) & (q_col)]

P         Q         R         S         T
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [117]:
df[(df["P"]>0) & (df["Q"]<0)]

P         Q         R         S         T
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [118]:
df.set_index("T")

P         Q         R         S
T                                                
 0.651118  2.706850  0.628133  0.907969  0.503826
 0.740122 -0.319318 -0.848077  0.605965 -2.018168
-0.933237  0.528813 -0.589001  0.188695 -0.758872
 0.683509  0.955057  0.190794  1.978757  2.605967
-0.134841  0.302665  1.693723 -1.706086 -1.159119

In [119]:
df

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [144]:
df={"A":[1,2,np.nan], "B":[1,3,5], "C":[9,np.nan,np.nan]}

In [145]:
df=pd.DataFrame(df)

In [146]:
df

A  B    C
0  1.0  1  9.0
1  2.0  3  NaN
2  NaN  5  NaN

In [147]:
df.dropna()

A  B    C
0  1.0  1  9.0

In [148]:
df.dropna(axis=1)

B
0  1
1  3
2  5

In [150]:
df.dropna(thresh=2)

A  B    C
0  1.0  1  9.0
1  2.0  3  NaN

In [152]:
df.fillna("NONE")

A  B     C
0     1  1     9
1     2  3  NONE
2  NONE  5  NONE

In [153]:
df=pd.DataFrame({"Company":["Google","Google","Microsoft","Microsoft","FaceBook","FaceBook"],
    "Person":["Sam","Charlie","Amy","Venessa","Cari","Sarah"],
    "Sales":[200,120,340,124,243,350]})

In [154]:
df

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Venessa    124
4   FaceBook     Cari    243
5   FaceBook    Sarah    350

In [156]:
df.groupby("Company").mean()

Sales
Company         
FaceBook   296.5
Google     160.0
Microsoft  232.0

In [157]:
df.groupby("Company").count()

Person  Sales
Company                 
FaceBook        2      2
Google          2      2
Microsoft       2      2

In [158]:
df.groupby("Company").describe()

Sales                                                        
          count   mean         std    min     25%    50%     75%    max
Company                                                                
FaceBook    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
Google      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
Microsoft   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [159]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [161]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [163]:
df=pd.concat([df1, df2, df3], axis=1)

In [164]:
df

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [165]:
df.fillna("0")

A   B   C   D   A   B   C   D    A    B    C    D
0   A0  B0  C0  D0   0   0   0   0    0    0    0    0
1   A1  B1  C1  D1   0   0   0   0    0    0    0    0
2   A2  B2  C2  D2   0   0   0   0    0    0    0    0
3   A3  B3  C3  D3   0   0   0   0    0    0    0    0
4    0   0   0   0  A4  B4  C4  D4    0    0    0    0
5    0   0   0   0  A5  B5  C5  D5    0    0    0    0
6    0   0   0   0  A6  B6  C6  D6    0    0    0    0
7    0   0   0   0  A7  B7  C7  D7    0    0    0    0
8    0   0   0   0   0   0   0   0   A8   B8   C8   D8
9    0   0   0   0   0   0   0   0   A9   B9   C9   D9
10   0   0   0   0   0   0   0   0  A10  B10  C10  D10
11   0   0   0   0   0   0   0   0  A11  B11  C11  D11

In [166]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [168]:
pd.merge(left, right, on=["key1", "key2"])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [169]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [170]:
df["col2"].unique()

array([444, 555, 666])

In [171]:
df["col2"].nunique()

3

In [172]:
df["col2"].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [173]:
def squareroot(x):
  return x**0.5
df["col1"].apply(squareroot)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
Name: col1, dtype: float64

In [174]:
df["col1"].apply(lambda x: x**0.5)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
Name: col1, dtype: float64